import logging

from motor.motor_asyncio import AsyncIOMotorDatabase
from pymongo import ASCENDING, DESCENDING, TEXT

logger = logging.getLogger(__name__)


async def ensure_indexes(database: AsyncIOMotorDatabase) -> None:
    try:
        await database.leads.create_index([("normalizedName", ASCENDING)])
        await database.leads.create_index([("city", ASCENDING)])
        await database.leads.create_index([("district", ASCENDING)])
        await database.leads.create_index([("pipelineStatus", ASCENDING)])
        await database.leads.create_index([("enrichmentStatus", ASCENDING)])
        await database.leads.create_index([("lastEnrichedAt", DESCENDING)])
        await database.leads.create_index([("priorityScore", DESCENDING)])
        await database.leads.create_index([("updatedAt", DESCENDING)])
        await database.leads.create_index(
            [("name", TEXT), ("normalizedName", TEXT), ("city", TEXT), ("district", TEXT)]
        )
        await database.lead_sources.create_index([("leadId", ASCENDING)])
        await database.lead_sources.create_index([("sourceType", ASCENDING), ("externalId", ASCENDING)])
        await database.lead_activities.create_index([("leadId", ASCENDING), ("createdAt", DESCENDING)])
        await database.lead_status_history.create_index([("leadId", ASCENDING), ("createdAt", DESCENDING)])
        await database.crawl_jobs.create_index([("startedAt", DESCENDING)])
        await database.crawl_jobs.create_index([("status", ASCENDING), ("startedAt", DESCENDING)])
        await database.source_registry.create_index([("sourceKey", ASCENDING)], unique=True)
        await database.source_registry.create_index([("isEnabled", ASCENDING), ("priority", ASCENDING)])
        await database.raw_discovery_items.create_index([("sourceKey", ASCENDING), ("externalId", ASCENDING)])
        await database.raw_discovery_items.create_index([("processed", ASCENDING), ("createdAt", DESCENDING)])
        await database.raw_discovery_items.create_index([("createdLeadId", ASCENDING)])
        await database.page_snapshots.create_index([("leadId", ASCENDING), ("capturedAt", DESCENDING)])
        await database.page_snapshots.create_index([("url", ASCENDING)])
        await database.feature_snapshots.create_index([("leadId", ASCENDING), ("createdAt", DESCENDING)])
        await database.dedup_candidates.create_index([("status", ASCENDING), ("score", DESCENDING)])
        await database.dedup_candidates.create_index([("leadIds", ASCENDING)])
        await database.dedup_candidates.create_index([("clusterId", ASCENDING)])
        await database.dedup_clusters.create_index([("status", ASCENDING), ("score", DESCENDING)])
        await database.dedup_clusters.create_index([("leadIds", ASCENDING)])
        await database.merge_events.create_index([("clusterId", ASCENDING)])
        await database.merge_events.create_index([("createdAt", DESCENDING)])
        await database.model_registry.create_index([("modelType", ASCENDING), ("isActive", ASCENDING)])
        await database.model_registry.create_index([("trainedAt", DESCENDING)])
        await database.training_runs.create_index([("startedAt", DESCENDING)])
        await database.training_runs.create_index([("status", ASCENDING), ("startedAt", DESCENDING)])
        await database.model_metrics.create_index([("modelId", ASCENDING)])
        await database.model_metrics.create_index([("trainingRunId", ASCENDING)])
        await database.active_model_config.create_index([("modelType", ASCENDING)], unique=True)
        await database.prediction_runs.create_index([("leadId", ASCENDING), ("createdAt", DESCENDING)])
        await database.prediction_runs.create_index([("modelId", ASCENDING)])
        await database.prediction_runs.create_index([("createdAt", DESCENDING)])
        await database.campaigns.create_index([("status", ASCENDING), ("updatedAt", DESCENDING)])
        await database.campaigns.create_index([("createdAt", DESCENDING)])
        await database.campaign_targets.create_index([("campaignId", ASCENDING), ("leadId", ASCENDING)], unique=True)
        await database.campaign_targets.create_index([("campaignId", ASCENDING), ("targetStatus", ASCENDING)])
        await database.message_templates.create_index([("channel", ASCENDING), ("isActive", ASCENDING)])
        await database.message_drafts.create_index([("campaignId", ASCENDING), ("draftStatus", ASCENDING)])
        await database.message_drafts.create_index([("leadId", ASCENDING), ("updatedAt", DESCENDING)])
        await database.campaign_events.create_index([("campaignId", ASCENDING), ("createdAt", DESCENDING)])
        await database.campaign_events.create_index([("leadId", ASCENDING), ("createdAt", DESCENDING)])
        await database.outbox_messages.create_index([("campaignId", ASCENDING), ("status", ASCENDING)])
        await database.outbox_messages.create_index([("draftId", ASCENDING)], unique=True)
        await database.outbox_messages.create_index([("status", ASCENDING), ("scheduledAt", ASCENDING)])
        await database.send_attempts.create_index([("outboxMessageId", ASCENDING), ("createdAt", DESCENDING)])
        await database.suppression_list.create_index([("identityType", ASCENDING), ("identityValue", ASCENDING)], unique=True)
        await database.delivery_events.create_index([("outboxMessageId", ASCENDING), ("createdAt", DESCENDING)])
    except Exception:
        logger.exception("mongo_index_creation_failed")
